controllers/PlayerController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\PlayerForm;
use app\models\Player;


class PlayerController extends Controller
{
    public function actionPlayer()
    {
        $model = new PlayerForm();
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {   
            $newmodel = new Player();
            $newmodel->UserName = $model->UserName;
            $newmodel->UserLastName = $model->UserLastName;
            $newmodel->DateOfBirth = $model->DateOfBirth;
            $newmodel->Status = $model->Status;
            $newmodel->CommandId = $model->CommandId;
            $newmodel->save();
            return $this->redirect(['site/view', 'id' => $model->CommandId]);
        }
        return $this->render('player',['model' => $model]);
    }
    
    public function actionUpdate($id)
    {
        $model = new Player();
        $newmodel = Player::findOne(['Id' => $id]);
        
        if($model->load(Yii::$app->request->post())&& $model->validate())
        {
            $newmodel->UserName = $model->UserName;
            $newmodel->UserLastName = $model->UserLastName;
            $newmodel->DateOfBirth = $model->DateOfBirth;
            $newmodel->Status = $model->Status;
            $newmodel->CommandId = $model->CommandId;
            $newmodel->save();
            return $this->redirect(['site/view', 'id' => $model->CommandId]);
        }
        return $this->render('player',['model' => $newmodel]);
    }
    
    public function actionDelete($id)
    {
        $model =  Player::findOne(['Id' => $id]);
        $model->delete();
        return $this->redirect(['site/view', 'id' => $model->CommandId]);
    }
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\CommandForm;
use app\models\Command;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
   
    public function actionView($id)
    {
        return $this->render('players', array('commandID' => $id));
    }
    
    public function actionUpdate($id)
    {
        $model = new Command();
        $newmodel = Command::findOne(['Id' => $id]);
        
        if($model->load(Yii::$app->request->post())&& $model->validate())
        {
            $newmodel->CommandName = $model->CommandName;
            $newmodel->YearCreate = $model->YearCreate;
            $newmodel->save();
            return $this->render('index');
        }
        return $this->render('command', ['model' => $newmodel]);
    }
    
    public function actionDelete($id)
    {
        $model =  Command::findOne(['Id' => $id]);
        $model->delete();
        return $this->render('index');
    }
    
    public function actionCommand()
    {
        $model = new CommandForm();
        $newCommand = new Command();
        
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $newCommand->CommandName = $model->CommandName;
            $newCommand->YearCreate = $model->YearCreate;
            $newCommand->save();
            return $this->render('index');
        }
        
        return $this->render('command', ['model' => $model]);
        
    }


    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/command.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use yii\jui\DatePicker;
?>
<h3>Command form</h3>

<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'CommandName')->textInput(['placeholder' => 'Command', 'style'=>'width:300px'])?>
<?= $form->field($model, 'YearCreate')->widget(DatePicker::classname(), 
    ['options' => ['placeholder' => 'Choise year', 'class' => 'form-control', 'style'=>'width:300px' ],'dateFormat' => 'yyyy'],
    
    [
        'language' => 'en',
])?>
<?= Html::submitButton('Submit', ['class' => 'btn btn-primary'])?>
<?php ActiveForm::end() ?>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\Command;
use yii\helpers\Html;
use yii\helpers\Url;


$this->title = 'My Yii Application';

$dataprovider = new ActiveDataProvider([
    'query' => Command::find(), 
    'pagination' => ['pageSize' => 10,],
]);

?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Command Manager</h1>
        <p class="lead">You have successfully created your Yii-powered application.</p>
    </div>

    <div class="body-content">
   
    <div align="right">
        <?= Html::a('Add command', ['/site/command'], ['class'=>'btn btn-primary']) ?>  
    </div>
     
    <?php
        echo GridView::widget([
            'dataProvider' => $dataprovider,
                'columns' => [
                'Id',
                ['attribute' => 'CommandName',
                
                'value' => function(Command $model)
                {
                    return Html::a(Html::encode($model->CommandName), Url::to(['site/view', 'id' => $model->Id]));
                }
                ,'format' => 'raw',
                ],
                'YearCreate',
                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Action',
                    'template' => '{view} {update} {delete}',
                    'buttons' => [
                        'view' => function($url, $model)
                        {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url);
                        },
                        
                        'update' => function ($url, $model)
                        {
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url);
                        },
                        
                        'delete' => function ($url, $model) 
                        {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url);
                        },
                    ],
                
                'urlCreator' => function ($action, $model, $url, $key)
                {
                    if($action === 'view')
                    {
                        $url = Url::to(['site/view', 'id' => $model->Id]);
                    }
                    
                    if($action === 'update')
                    {
                        $url = Url::to(['site/update', 'id' => $model->Id]);
                    }
                    
                    if($action === 'delete')
                    {
                        $url = Url::to(['site/delete', 'id' => $model->Id]);
                    }
                    return $url;
                }
                ],
            ],
        ]);
        ?>
        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/players.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\Command;
use app\models\Player;
use yii\helpers\Url;
use yii\web\View;

$this->title = 'Players';
$this->params['breadcrumbs'][] = $this->title;

$dataprovider = new ActiveDataProvider([
    'query' => Player::find()->where(['commandid' => $commandID]), 
    'pagination' => ['pageSize' => 10,],
]);
 ?>    

<?php
$command = new Command();
echo "<h2>"."Command is ".$command->GetCommandName($commandID)->CommandName."</h2>";
?>

<div align="right">
    <?= Html::a('Add player', ['/player/player'], ['class'=>'btn btn-primary']) ?>  
</div>

<?php
echo GridView::widget([
    'dataProvider' => $dataprovider,
    'columns' => [
        'id',
       'UserName',
       'UserLastName',
       'DateOfBirth',
       'Status',
       ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Action',
                    'template' => '{update} {delete}',
                    'buttons' => [
                        'update' => function ($url, $model)
                        {
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Url::to(['player/update', 'id' => $model->id]));
                        },
                        
                        'delete' => function ($url, $model) 
                        {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['player/delete', 'id' => $model->id]));
                        },
                    ],
                ],
    ],
]);

?>